### ISSUE TITLE
记仇表情包使用报错

### ISSUE THREAD

**Issue by jcjrobert** [MeetWq/nonebot-plugin-memes#1]
日志显示UnicodeEncodeError: 'locale' codec can't encode character '\u5e74' in position 2: encoding error
也就是time.strftime不支持中文
我改成了text = f"{datetime.today().strftime('%Y年%m月%d日'.encode('unicode_escape').decode('utf8')).encode('utf-8').decode('unicode_escape')} 晴\n{texts[0]}\n这个仇我先记下了"
你可以参考改进一下

还有你一口气做这么多表情包，tqldl

**Comment by jcjrobert** [comment]
同时建议菜单可以根据文字弹性调整

**Comment by MeetWq** [comment]
感谢反馈，bug我等下修

关于建议：
①“表情包制作”菜单的图片目前就是根据表情包列表实时生成的
②多段文字是用 shlex 分割的，也就是 shell 风格，对于有空格的情况可以用 `\` 转义，或者用引号包起来，比如 `Hello,\ World` 或 `"Hello, World"`

三个表情包制作因为在实现方式和调用方式上都有些区别，所以分开了，合在一起内容太多，感觉会比较乱，暂时先这样吧（

欢迎添加表情包，也可以发issue提交素材，我来整合

**Comment by jcjrobert** [comment]
记仇设置一下文字行数阈值吧，被群友玩坏了（）

**Comment by MeetWq** [comment]
草w

**Comment by jcjrobert** [comment]
来自群友发现，当gif仅用\ 作为单独一段时会报错ValueError: No escaped character

**Comment by MeetWq** [comment]
用 try except 包了一下
可以用 `\\` 或者 `"\"` 表示反斜杠
