### ISSUE TITLE
Object of type BytesIO is not JSON serializable

### ISSUE THREAD

**Issue by liaobozheng** [MeetWq/nonebot-plugin-memes#3]
大佬大佬，我用的是真寻bot，出现了报错，请问该如何解决呢
![图片](https://user-images.githubusercontent.com/48149171/147907590-58ad4a51-29f3-49ea-86e7-1bdaefe564c1.png)

**Comment by MeetWq** [comment]
因为真寻的nonebot版本比较低，图片不能直接传BytesIO
可以把
```
await matcher.finish(MessageSegment.image(msg))
```
改成
```
await matcher.finish(MessageSegment.image(f"base64://{base64.b64encode(msg.getvalue()).decode()}"))
```
开头加上 `import base64`

**Comment by liaobozheng** [comment]
成功了啊啊啊！！！
大佬太强了！！！！
orz
